### Start by opening a file that contains historical data of the stock symbol SPY from 1/19/2010 to 1/17/2024.

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing

# Open file as a DataFrame
file_path = '/kaggle/input/spy-historical-data/SPY.csv'
SPY = pd.read_csv(file_path)

# Print data
SPY

,Date,Open,High,Low,Close,Adj Close,Volume
0,2010-01-19,113.620003,115.129997,113.589996,115.059998,88.459953,139172700
1,2010-01-20,114.279999,114.449997,112.980003,113.889999,87.560463,216490200
2,2010-01-21,113.919998,114.269997,111.559998,111.699997,85.876747,344859600
3,2010-01-22,111.199997,111.739998,109.089996,109.209999,83.962410,345942400
4,2010-01-25,110.209999,110.410004,109.410004,109.769997,84.392944,186937500
...,...,...,...,...,...,...,...
3518,2024-01-10,474.160004,477.450012,473.869995,476.559998,476.559998,67310600
3519,2024-01-11,477.589996,478.119995,472.260010,476.350006,476.350006,77940700
3520,2024-01-12,477.839996,478.600006,475.230011,476.679993,476.679993,57944000
3521,2024-01-16,475.260010,476.609985,473.059998,474.929993,474.929993,85014900
3522,2024-01-17,471.820007,472.790009,469.875000,472.290009,472.290009,62499905

### I see that there's opening values and closing values for every market day.
### So I create a column with the change in price (closing price - opening price).
### Also, I add another column with the percent difference for better visualization.

In [2]:
# Calculate diff and %_diff
SPY['Diff'] = SPY['Close'] - SPY['Open']
SPY['%'] = ((SPY['Diff'] / SPY['Open']) * 100).round(2)

# Print data
SPY

,Date,Open,High,Low,Close,Adj Close,Volume,Diff,%
0,2010-01-19,113.620003,115.129997,113.589996,115.059998,88.459953,139172700,1.439995,1.27
1,2010-01-20,114.279999,114.449997,112.980003,113.889999,87.560463,216490200,-0.390000,-0.34
2,2010-01-21,113.919998,114.269997,111.559998,111.699997,85.876747,344859600,-2.220001,-1.95
3,2010-01-22,111.199997,111.739998,109.089996,109.209999,83.962410,345942400,-1.989998,-1.79
4,2010-01-25,110.209999,110.410004,109.410004,109.769997,84.392944,186937500,-0.440002,-0.40
...,...,...,...,...,...,...,...,...,...
3518,2024-01-10,474.160004,477.450012,473.869995,476.559998,476.559998,67310600,2.399994,0.51
3519,2024-01-11,477.589996,478.119995,472.260010,476.350006,476.350006,77940700,-1.239990,-0.26
3520,2024-01-12,477.839996,478.600006,475.230011,476.679993,476.679993,57944000,-1.160003,-0.24
3521,2024-01-16,475.260010,476.609985,473.059998,474.929993,474.929993,85014900,-0.330017,-0.07
3522,2024-01-17,471.820007,472.790009,469.875000,472.290009,472.290009,62499905,0.470002,0.10

### Now I will choose a more specific time span.

In [3]:
# Choose start and end date
start_date = '2023-01-01'
end_date = '2024-01-01'

# Filter data
SPY = SPY[(SPY['Date'] >= start_date) & (SPY['Date'] <= end_date)]

# Print table
SPY

,Date,Open,High,Low,Close,Adj Close,Volume,Diff,%
3262,2023-01-03,384.369995,386.429993,377.829987,380.820007,375.118713,74850700,-3.549988,-0.92
3263,2023-01-04,383.179993,385.880005,380.000000,383.760010,378.014709,85934100,0.580017,0.15
3264,2023-01-05,381.720001,381.839996,378.760010,379.380005,373.700287,76970500,-2.339996,-0.61
3265,2023-01-06,382.609985,389.250000,379.410004,388.079987,382.270020,104189600,5.470002,1.43
3266,2023-01-09,390.369995,393.700012,387.670013,387.859985,382.053253,73978100,-2.510010,-0.64
...,...,...,...,...,...,...,...,...,...
3507,2023-12-22,473.859985,475.380005,471.700012,473.649994,473.649994,67126600,-0.209991,-0.04
3508,2023-12-26,474.070007,476.579987,473.989990,475.649994,475.649994,55387000,1.579987,0.33
3509,2023-12-27,475.440002,476.660004,474.890015,476.510010,476.510010,68000300,1.070008,0.23
3510,2023-12-28,476.880005,477.549988,476.260010,476.690002,476.690002,77158100,-0.190003,-0.04
3511,2023-12-29,476.489990,477.029999,473.299988,475.309998,475.309998,122234100,-1.179992,-0.25

### What I investigate here is how often the stock rises and drops after three losing days.
### In the code below, I register in a new table all the times that the stock had three losing days.
### I also register the next day, to see if it was a gain or loss.

In [4]:
# Initialize necessary variables
pattern = pd.DataFrame([])
profit = 0
bull_days = 0
bear_days = 0

# This iterates over all the data and catches the pattern wanted
i = 3
while i < len(SPY):
    if SPY.iloc[i - 3]['%'] < 0 and SPY.iloc[i - 2]['%'] < 0 and SPY.iloc[i - 1]['%'] < 0:
        pattern = pd.concat([pattern, SPY.iloc[i - 3:i + 1]], ignore_index=True)
        profit += SPY.iloc[i]['%']
        if SPY.iloc[i]['%'] > 0:
            bull_days += 1 # Add to bull_days if the day after three losing days was a gain
        else:
            bear_days += 1 # Add to bear_days if the day after three losing days was just another loss
        i += 3
    i += 1
    
# Print all days that match the pattern
pattern

,Date,Open,High,Low,Close,Adj Close,Volume,Diff,%
0,2023-01-17,398.480011,400.230011,397.059998,397.769989,391.814911,62677300,-0.710022,-0.18
1,2023-01-18,399.010010,400.119995,391.279999,391.489990,385.628937,99632300,-7.520020,-1.88
2,2023-01-19,389.359985,391.079987,387.260010,388.640015,382.821625,86958900,-0.719970,-0.18
3,2023-01-20,390.100006,396.040009,388.380005,395.880005,389.953247,91806400,5.779999,1.48
4,2023-02-21,403.059998,404.160004,398.820007,399.089996,393.115204,82655900,-3.970002,-0.98
5,2023-02-22,399.519989,401.130005,397.019989,398.540009,392.573425,83742300,-0.979980,-0.25
6,2023-02-23,401.559998,402.200012,396.250000,400.660004,394.661682,96242400,-0.899994,-0.22
7,2023-02-24,395.420013,397.250000,393.640015,396.380005,390.445740,108194400,0.959992,0.24
8,2023-02-27,399.869995,401.290009,396.750000,397.730011,391.775543,80444700,-2.139984,-0.54
9,2023-02-28,397.230011,399.279999,396.149994,396.260010,390.327576,96438600,-0.970001,-0.24
10,2023-03-01,395.410004,396.690002,393.380005,394.739990,388.830292,99706800,-0.670014,-0.17
11,2023-03-02,392.679993,398.690002,392.329987,397.809998,391.854340,85127800,5.130005,1.31
12,2023-05-02,414.769989,414.820007,407.820007,410.839996,406.233795,103998500,-3.929993,-0.95
13,2023-05-03,411.359985,413.869995,407.769989,408.019989,403.445374,91531800,-3.339996,-0.81
14,2023-05-04,406.929993,407.269989,403.739990,405.130005,400.587799,94901900,-1.799988,-0.44
15,2023-05-05,408.910004,413.720001,408.640015,412.630005,408.003723,87844000,3.720001,0.91
16,2023-05-08,412.970001,413.239990,411.279999,412.739990,408.112427,50046800,-0.230011,-0.06
17,2023-05-09,411.130005,412.089996,410.690002,410.929993,406.322754,49220100,-0.200012,-0.05
18,2023-05-10,413.880005,414.540009,408.869995,412.850006,408.221252,96142900,-1.029999,-0.25
19,2023-05-11,411.950012,412.429993,409.970001,412.130005,407.509277,70157100,0.179993,0.04
20,2023-05-23,417.079987,418.720001,413.679993,414.089996,409.447357,86383500,-2.989991,-0.72
21,2023-05-24,412.420013,412.820007,409.880005,411.089996,406.480957,89213700,-1.330017,-0.32
22,2023-05-25,414.739990,416.160004,412.410004,414.649994,410.001038,90961600,-0.089996,-0.02
23,2023-05-26,415.329987,420.769989,415.250000,420.019989,415.310822,93830000,4.690002,1.13
24,2023-06-16,443.019989,443.609985,438.970001,439.459991,436.147003,114121300,-3.559998,-0.80
25,2023-06-20,437.450012,438.369995,435.029999,437.179993,433.884186,76160400,-0.270019,-0.06
26,2023-06-21,436.160004,436.989990,434.329987,434.940002,431.661102,76982300,-1.220002,-0.28
27,2023-06-22,433.950012,436.619995,433.600006,436.510010,433.219269,70637200,2.559998,0.59
28,2023-08-15,446.269989,446.640015,442.299988,442.890015,439.551178,75707500,-3.379974,-0.76
29,2023-08-16,442.459991,444.179993,439.529999,439.640015,436.325653,80107200,-2.819976,-0.64
30,2023-08-17,441.160004,441.429993,435.750000,436.290009,433.000916,95711300,-4.869995,-1.10
31,2023-08-18,433.369995,437.570007,433.010010,436.500000,433.209320,98758400,3.130005,0.72
32,2023-08-31,451.649994,452.829987,450.160004,450.350006,446.954926,66084600,-1.299988,-0.29
33,2023-09-01,453.170013,453.670013,449.679993,451.190002,447.788574,58875700,-1.980011,-0.44
34,2023-09-05,450.730011,451.059998,449.170013,449.239990,445.853271,55166200,-1.490021,-0.33
35,2023-09-06,448.399994,448.510010,443.809998,446.220001,442.856018,70758500,-2.179993,-0.49
36,2023-09-20,444.010010,444.440002,438.429993,438.640015,436.868774,82562600,-5.369995,-1.21
37,2023-09-21,435.700012,435.970001,431.230011,431.390015,429.648041,103976100,-4.309997,-0.99
38,2023-09-22,432.450012,434.100006,429.989990,430.420013,428.681976,100829700,-2.029999,-0.47
39,2023-09-25,429.170013,432.269989,428.720001,432.230011,430.484650,70874500,3.059998,0.71
40,2023-10-18,434.190002,435.179993,429.089996,430.209991,428.472778,93559800,-3.980011,-0.92
41,2023-10-19,430.950012,432.820007,425.730011,426.429993,424.708038,121323000,-4.520019,-1.05
42,2023-10-20,425.980011,426.540009,421.079987,421.190002,419.489227,123845800,-4.790009,-1.12
43,2023-10-23,419.609985,424.450012,417.799988,420.459991,418.762146,92035100,0.850006,0.20
44,2023-10-25,421.890015,421.920013,417.019989,417.549988,415.863892,94223200,-4.340027,-1.03
45,2023-10-26,416.450012,417.329987,411.600006,412.549988,410.884094,115156800,-3.900024,-0.94
46,2023-10-27,414.190002,414.600006,409.209991,410.679993,409.021637,107367700,-3.510009,-0.85
47,2023-10-30,413.559998,416.679993,412.220001,415.589996,413.911835,86562700,2.029998,0.49

### Now I can say clearly how many bull days and bear days the stock had after every 3-day loss streak in the chosen time frame.

In [5]:
print("Profit: " + str(profit) + "%")
print("Bull days: " + str(bull_days))
print("Bear days: " + str(bear_days))

Profit: 7.33%
Bull days: 11
Bear days: 1